Repository Tave12st-Backend-Study/jpa-study, pull requests merged in 2023-09, with the labels that each got.

#28 [Week2][Chapter4~5] Choi SongHee
  최송희/.idea/.gitignore
  최송희/.idea/misc.xml
  최송희/.idea/modules.xml
  최송희/.idea/vcs.xml
  최송희/.idea/최송희.iml
  최송희/ex1-hello-jpa2/.gitignore
  최송희/ex1-hello-jpa2/.idea/.gitignore
  최송희/ex1-hello-jpa2/.idea/encodings.xml
  최송희/ex1-hello-jpa2/.idea/misc.xml
  최송희/ex1-hello-jpa2/.idea/vcs.xml
  최송희/ex1-hello-jpa2/pom.xml
  최송희/ex1-hello-jpa2/src/main/java/jpabasic/Main.java
  최송희/ex1-hello-jpa2/src/main/java/jpabasic/Member.java
  최송희/ex1-hello-jpa2/src/main/resources/META-INF/persistence.xml
  최송희/jpashop.mv.db
  최송희/jpashop/.gitignore
  최송희/jpashop/.idea/.gitignore
  최송희/jpashop/.idea/encodings.xml
  최송희/jpashop/.idea/misc.xml
  최송희/jpashop/.idea/vcs.xml
  최송희/jpashop/pom.xml
  최송희/jpashop/src/main/java/jpabook/Item.java
  최송희/jpashop/src/main/java/jpabook/Main.java
  최송희/jpashop/src/main/java/jpabook/Member.java
  최송희/jpashop/src/main/java/jpabook/Order.java
  최송희/jpashop/src/main/java/jpabook/OrderItem.java
  최송희/jpashop/src/main/java/jpabook/OrderStatus.java
  최송희/jpashop/src/main/resources/META-INF/persistence.xml
  최송희/섹션3/영속성 컨텍스트 1.md
  최송희/섹션4/내용정리.md
  최송희/섹션5/내용정리.md
Labels: 최송희, Pull Request

#26 [Week2][Chapter4~5] Leejaepyo
  이재표/basic/ex1-hello-jpa/src/main/java/hellojpa/Item.java
  이재표/basic/ex1-hello-jpa/src/main/java/hellojpa/JpaMain.java
  이재표/basic/ex1-hello-jpa/src/main/java/hellojpa/Member.java
  이재표/basic/ex1-hello-jpa/src/main/java/hellojpa/Order.java
  이재표/basic/ex1-hello-jpa/src/main/java/hellojpa/OrderItem.java
  이재표/basic/ex1-hello-jpa/src/main/java/hellojpa/OrderStatus.java
  이재표/basic/ex1-hello-jpa/src/main/java/hellojpa/RoleType.java
  이재표/basic/ex1-hello-jpa/src/main/java/hellojpa/Team.java
  이재표/basic/ex1-hello-jpa/src/main/resources/META-INF/persistence.xml
  이재표/basic/ex1-hello-jpa/target/classes/META-INF/persistence.xml
  이재표/basic/ex1-hello-jpa/target/classes/hellojpa/Item.class
  이재표/basic/ex1-hello-jpa/target/classes/hellojpa/JpaMain.class
  이재표/basic/ex1-hello-jpa/target/classes/hellojpa/Member.class
  이재표/basic/ex1-hello-jpa/target/classes/hellojpa/Order.class
  이재표/basic/ex1-hello-jpa/target/classes/hellojpa/OrderItem.class
  이재표/basic/ex1-hello-jpa/target/classes/hellojpa/OrderStatus.class
  이재표/basic/ex1-hello-jpa/target/classes/hellojpa/RoleType.class
  이재표/basic/ex1-hello-jpa/target/classes/hellojpa/Team.class
Labels: 이재표, Pull Request

#42 [Week3][Chapter6~7] Limjunhyoung
  임준형/basic/reviewjpa/src/main/java/reviewjpa/JpaMain.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/Locker.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/Member.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/MemberProduct.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/Product.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/Team.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/superclass/Album.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/superclass/BaseEntity.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/superclass/Book.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/superclass/Item.java
  임준형/basic/reviewjpa/src/main/java/reviewjpa/superclass/Movie.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/JpaMain.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/BaseEntity.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/Category.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/Delivery.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/DeliveryStatus.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/Item.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/Member.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/Order.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/OrderItem.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/item/Album.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/item/Book.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/item/Item.java
  임준형/basicjpabook/src/main/java/jpabook/jpashop/domain/item/Movie.java
Labels: 임준형, Pull Request
