Repository Tave12st-Backend-Study/jpa-study, pull requests merged in 2023-11, with the labels that each got.

#99 [Week8][Chap1~6] jinu Yi
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/build.gradle
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/JpashopJinuApplication.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/api/MemberApiController.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/api/OrderApiController.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/api/OrderSimpleApiController.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/Category.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/Delivery.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/DeliveryStatus.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/Member.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/Order.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/OrderItem.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/OrderSearch.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/item/Album.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/item/Book.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/domain/item/Item.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/initDb.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/MemberRepository.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/MemberRepositoryOld.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/OrderRepository.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/order/query/OrderFlatDto.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/order/query/OrderItemQueryDto.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/order/query/OrderQueryDto.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/order/query/OrderQueryRepository.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/order/simplequery/OrderSimpleQueryDto.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/repository/order/simplequery/OrderSimpleQueryRepository.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/service/ItemService.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/service/MemberService.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/java/jpabook_jinu/jpashop_jinu/service/OrderService.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/main/resources/application.yml
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/test/java/jpabook_jinu/jpashop_jinu/MemberRepositoryTest.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/test/java/jpabook_jinu/jpashop_jinu/service/MemberServiceTest.java
  이진우/jpa_web_jinu/jpashop_jinu/jpashop_jinu/src/test/java/jpabook_jinu/jpashop_jinu/service/OrderServiceTest.java
Labels: 이진우, Pull Request

#100 [Week8][Chap1~6] Kimjiyun
  김지윤/jpashop2/build.gradle
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/QAddress.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/QCategory.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/QDelivery.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/QMember.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/QOrder.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/QOrderItem.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/item/QAlbum.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/item/QBook.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/item/QItem.java
  김지윤/jpashop2/src/main/generated/jpabook/jpashop/domain/item/QMovie.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/InitDb.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/JpashopApplication.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/api/MemberApiController.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/api/OrderApiController.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/api/OrderSimpleApiController.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/domain/Delivery.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/domain/Member.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/domain/OrderItem.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/MemberRepository.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/MemberRepositoryOld.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/OrderRepository.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/order/query/OrderFlatDto.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/order/query/OrderItemQueryDto.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/order/query/OrderQueryDto.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/order/query/OrderQueryRepository.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/order/simplequery/OrderSimpleQueryDto.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/repository/order/simplequery/OrderSimpleQueryRepository.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/service/MemberService.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/service/OrderService.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/service/query/OrderDto.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/service/query/OrderItemDto.java
  김지윤/jpashop2/src/main/java/jpabook/jpashop/service/query/OrderQueryService.java
  김지윤/jpashop2/src/main/resources/application.yml
  김지윤/jpashop2/src/test/java/jpabook/jpashop/service/MemberServiceTest.java
Labels: 김지윤, Pull Request

#98 [Week 8][Chap1~6] Minyoungsong
  송민영/jpashop01/.gitignore
  송민영/jpashop01/build.gradle
  송민영/jpashop01/src/main/java/jpabook/jpashop01/InitDb.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/Jpashop01Application.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/api/MemberApiController.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/api/OrderApiController.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/api/OrderSimpleApiController.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/domain/Delivery.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/domain/Member.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/domain/Order.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/domain/OrderItem.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/MemberRepository.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/MemberRepositoryOld.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/OrderRepository.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/order/query/OrderFlatDto.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/order/query/OrderItemQueryDto.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/order/query/OrderQueryDto.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/order/query/OrderQueryRepository.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/order/simplequery/OrderSimpleQueryDto.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/repository/order/simplequery/OrderSimpleQueryRepository.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/service/MemberService.java
  송민영/jpashop01/src/main/java/jpabook/jpashop01/service/OrderService.java
  송민영/jpashop01/src/main/resources/application.yml
  송민영/jpashop01/src/test/java/jpabook/jpashop01/service/MemberServiceTest.java
Labels: 송민영, Pull Request

#103 [Week8][Chap1~6] Leejaepyo
  이재표/spring-data-jpa1/jpashop/build.gradle
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/JpashopApplication.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/api/MemberApiController.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/api/OrderApiController.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/api/OrderSimpleApiController.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/controller/BookForm.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/controller/HomeController.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/controller/ItemController.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/controller/MemberController.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/controller/MemberForm.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/controller/OrderController.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/domain/Address.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/domain/Delivery.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/domain/Member.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/domain/Order.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/domain/OrderItem.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/domain/item/Item.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/exception/NotEnoughStockException.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/initDb.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/ItemRepository.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/MemberRepository.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/OrderRepository.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/OrderSearch.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/order/query/OrderFlatDto.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/order/query/OrderItemQueryDto.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/order/query/OrderQueryDto.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/order/query/OrderQueryRepository.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/repository/order/simplequery/SimpleOrderQueryDto.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/service/ItemService.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/service/MemberService.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/service/OrderService.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/service/UpdateItemDto.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/service/query/OrderDto.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/service/query/OrderItemDto.java
  이재표/spring-data-jpa1/jpashop/src/main/java/jpabook/jpashop/service/query/OrderQueryService.java
  이재표/spring-data-jpa1/jpashop/src/main/resources/application.yml
  이재표/spring-data-jpa1/jpashop/src/main/resources/static/css/bootstrap-grid.css
  이재표/spring-data-jpa1/jpashop/src/main/resources/static/css/bootstrap-reboot.css
  이재표/spring-data-jpa1/jpashop/src/main/resources/static/css/bootstrap.css
  이재표/spring-data-jpa1/jpashop/src/main/resources/static/css/jumbotron-narrow.css
  이재표/spring-data-jpa1/jpashop/src/main/resources/static/js/bootstrap.bundle.js
  이재표/spring-data-jpa1/jpashop/src/main/resources/static/js/bootstrap.js
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/fragments/bodyHeader.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/fragments/footer.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/fragments/header.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/hello.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/home.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/items/createItemForm.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/items/itemList.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/items/updateItemForm.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/members/createMemberForm.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/members/memberList.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/order/orderForm.html
  이재표/spring-data-jpa1/jpashop/src/main/resources/templates/order/orderList.html
  이재표/spring-data-jpa1/jpashop/src/test/java/jpabook/jpashop/MemberRepositoryTest.java
  이재표/spring-data-jpa1/jpashop/src/test/java/jpabook/jpashop/service/ItemUpdateTest.java
  이재표/spring-data-jpa1/jpashop/src/test/java/jpabook/jpashop/service/MemberServiceTest.java
  이재표/spring-data-jpa1/jpashop/src/test/java/jpabook/jpashop/service/OrderServiceTest.java
Labels: 이재표, Pull Request

#101 [Week8][Chap1~6] ChoiSongHee
  최송희/jpashop/.idea/workspace.xml
  최송희/jpashop/build.gradle
  최송희/jpashop/src/main/java/jpabook/jpashop/InitDb.java
  최송희/jpashop/src/main/java/jpabook/jpashop/JpashopApplication.java
  최송희/jpashop/src/main/java/jpabook/jpashop/api/MemberApiController.java
  최송희/jpashop/src/main/java/jpabook/jpashop/api/OrderApiController.java
  최송희/jpashop/src/main/java/jpabook/jpashop/api/OrderSimpleApiController.java
  최송희/jpashop/src/main/java/jpabook/jpashop/domain/Member.java
  최송희/jpashop/src/main/java/jpabook/jpashop/domain/Order.java
  최송희/jpashop/src/main/java/jpabook/jpashop/domain/OrderItem.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/MemberRepository.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/MemberRepositoryOld.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/OrderRepository.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/order/query/OrderFlatDto.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/order/query/OrderItemQueryDto.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/order/query/OrderQueryDto.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/order/query/OrderQueryRepository.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/order/simplequery/OrderSimpleQueryDto.java
  최송희/jpashop/src/main/java/jpabook/jpashop/repository/order/simplequery/OrderSimpleQueryRepository.java
  최송희/jpashop/src/main/java/jpabook/jpashop/service/MemberService.java
  최송희/jpashop/src/main/java/jpabook/jpashop/service/OrderService.java
  최송희/jpashop/src/main/resources/application.yml
  최송희/실전!스트링부트와 JPA활용/1편.md
  최송희/실전!스트링부트와 JPA활용/2편.md
  최송희/추가적인 조사/실전웹활용 조사.md
  최송희/퀴즈/실전
  최송희/퀴즈/실전웹활용 퀴즈.md
Labels: 최송희, Pull Request

#110 [Week9][Chap1~8] Choisonghee
  최송희/data-jpa/.gitignore
  최송희/data-jpa/build.gradle
  최송희/data-jpa/gradle/wrapper/gradle-wrapper.jar
  최송희/data-jpa/gradle/wrapper/gradle-wrapper.properties
  최송희/data-jpa/gradlew
  최송희/data-jpa/gradlew.bat
  최송희/data-jpa/settings.gradle
  최송희/data-jpa/src/main/java/study/datajpa/DataJpaApplication.java
  최송희/data-jpa/src/main/java/study/datajpa/controller/MemberController.java
  최송희/data-jpa/src/main/java/study/datajpa/dto/MemberDto.java
  최송희/data-jpa/src/main/java/study/datajpa/entity/BaseEntity.java
  최송희/data-jpa/src/main/java/study/datajpa/entity/Item.java
  최송희/data-jpa/src/main/java/study/datajpa/entity/JpaBaseEntity.java
  최송희/data-jpa/src/main/java/study/datajpa/entity/Member.java
  최송희/data-jpa/src/main/java/study/datajpa/entity/Team.java
  최송희/data-jpa/src/main/java/study/datajpa/repository/ItemRepository.java
  최송희/data-jpa/src/main/java/study/datajpa/repository/MemberJpaRepository.java
  최송희/data-jpa/src/main/java/study/datajpa/repository/MemberProjection.java
  최송희/data-jpa/src/main/java/study/datajpa/repository/MemberRepository.java
  최송희/data-jpa/src/main/java/study/datajpa/repository/MemberRepositoryCustom.java
  최송희/data-jpa/src/main/java/study/datajpa/repository/MemberRepositoryImpl.java
  최송희/data-jpa/src/main/java/study/datajpa/repository/TeamJpaRepository.java
  최송희/data-jpa/src/main/java/study/datajpa/repository/TeamRepository.java
  최송희/data-jpa/src/main/resources/application.yml
  최송희/data-jpa/src/test/java/study/datajpa/DataJpaApplicationTests.java
  최송희/data-jpa/src/test/java/study/datajpa/entity/MemberTest.java
  최송희/data-jpa/src/test/java/study/datajpa/repository/ItemRepositoryTest.java
  최송희/data-jpa/src/test/java/study/datajpa/repository/MemberJpaRepositoryTest.java
  최송희/data-jpa/src/test/java/study/datajpa/repository/MemberRepositoryTest.java
  최송희/jpashop/.idea/workspace.xml
  최송희/추가적인 조사/실전웹활용2 조사.md
  최송희/퀴즈/실전
  최송희/퀴즈/실전웹활용2 퀴즈.md
Labels: 최송희, Pull Request

#112 [Week9][Chap1~7] Limjunhyoung
  임준형/SpringDataJpa/.gitignore
  임준형/SpringDataJpa/build.gradle
  임준형/SpringDataJpa/gradle/wrapper/gradle-wrapper.jar
  임준형/SpringDataJpa/gradle/wrapper/gradle-wrapper.properties
  임준형/SpringDataJpa/gradlew
  임준형/SpringDataJpa/gradlew.bat
  임준형/SpringDataJpa/settings.gradle
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/SpringDataJpaApplication.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/controller/MemberController.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/entity/BaseEntity.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/entity/BaseTimeEntity.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/entity/Item.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/entity/JpaBaseEntity.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/entity/Member.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/entity/Team.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/ItemRepository.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/MemberJpaRepository.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/MemberRepository.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/TeamJpaRepository.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/TeamRepository.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/custom/MemberRepositoryCustom.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/custom/MemberRepositoryImpl.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/dto/BaseEntityConfig.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/dto/MemberDto.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/projections/MemberProjection.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/projections/UserNameOnly.java
  임준형/SpringDataJpa/src/main/java/study/SpringDataJpa/repository/projections/UserNameOnlyDto.java
  임준형/SpringDataJpa/src/test/java/study/SpringDataJpa/SpringDataJpaApplicationTests.java
  임준형/SpringDataJpa/src/test/java/study/SpringDataJpa/entity/MemberTest.java
  임준형/SpringDataJpa/src/test/java/study/SpringDataJpa/repository/ItemRepositoryTest.java
  임준형/SpringDataJpa/src/test/java/study/SpringDataJpa/repository/MemberJpaRepositoryTest.java
  임준형/SpringDataJpa/src/test/java/study/SpringDataJpa/repository/MemberRepositoryTest.java
  임준형/SpringDataJpa/src/test/java/study/SpringDataJpa/repository/TeamJpaRepositoryTest.java
  임준형/real-spring-jpa2/src/main/java/jpashop/realspringjpa2/repository/PreMemberRepository.java
  임준형/real-spring-jpa2/src/main/resources/application.yml
Labels: 임준형, Pull Request
